import hana from "./images/hana.jpg";
import lauren from "./images/lauren.jpg";
import song from "./images/song.jpg";

export interface SongsModel {
  id: number;
  title: string;
  artist: string;
  //image: string; // Assuming p1_img and p2_img are of string type
  album: string;
  genre: string;
  releaseYear: Date | string;
  duration: number;
  image: string;
}
export let allSongs: SongsModel[] = [
  {
    id: 1,
    title: "Kahin",
    artist: "HAna Tekle",
    album: "Habte semay",
    genre: "walth",
    releaseYear: new Date(),
    duration: 5.55,
    image: hana,
  },
  {
    id: 2,
    title: "This Girl",
    artist: "Lauren Daigle",
    album: "Look Up Child",
    genre: "contemporary Christian music",
    releaseYear: new Date(),
    duration: 3.03,
    image: lauren,
  },
  {
    id: 3,
    title: "Like a Rolling Stone",
    artist: "Bob Dylan",
    album: "Highway 61 Revisited",
    genre: "Rock",
    releaseYear: new Date(),
    duration: 6.13,
    image: song,
  },
  {
    id: 4,
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    genre: "Pop",
    releaseYear: new Date(),
    duration: 4.54,
    image: song,
  },
  {
    id: 5,
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    genre: "Rock",
    releaseYear: new Date(),
    duration: 6.3,
    image: song,
  },
  {
    id: 6,
    title: "Hey Jude",
    artist: "The Beatles",
    album: "The Beatles (White Album)",
    genre: "Rock",
    releaseYear: new Date(),
    duration: 7.11,
    image: song,
  },
  {
    id: 7,
    title: "Purple Haze",
    artist: "Jimi Hendrix",
    album: "Are You Experienced",
    genre: "Rock",
    releaseYear: new Date(),
    duration: 2.5,
    image: song,
  },
  {
    id: 8,
    title: "Superstition",
    artist: "Stevie Wonder",
    album: "Talking Book",
    genre: "Soul",
    releaseYear: new Date(),
    duration: 4.26,
    image: song,
  },
  {
    id: 9,
    title: "Boogie Wonderland",
    artist: "Earth, Wind & Fire",
    album: "I Am",
    genre: "Disco",
    releaseYear: new Date(),
    duration: 4.48,
    image: song,
  },
  {
    id: 10,
    title: "Wonderwall",
    artist: "Oasis",
    album: "What's the Story Morning Glory?",
    genre: "Rock",
    releaseYear: new Date(),
    duration: 4.18,
    image: song,
  },
  {
    id: 11,
    title: "Eregna",
    artist: "HAna Tekle",
    album: "Habte semay",
    genre: "walth",
    releaseYear: new Date(),
    duration: 5.55,
    image: hana,
  },
  {
    id: 12,
    title: "Bicha Liben",
    artist: "HAna Tekle",
    album: "Habte semay",
    genre: "walth",
    releaseYear: new Date(),
    duration: 5.55,
    image: hana,
  },
  {
    id: 13,
    title: "Ewinetina Ewnet",
    artist: "HAna Tekle",
    album: "Habte semay",
    genre: "walth",
    releaseYear: new Date(),
    duration: 5.55,
    image: hana,
  },
  {
    id: 14,
    title: "Regichalew",
    artist: "HAna Tekle",
    album: "Habte semay",
    genre: "walth",
    releaseYear: new Date(),
    duration: 5.55,
    image: hana,
  },
  {
    id: 15,
    title: "Filega (Motive)",
    artist: "HAna Tekle",
    album: "Habte semay",
    genre: "walth",
    releaseYear: new Date(),
    duration: 5.55,
    image: hana,
  },
  {
    id: 16,
    title: "Eregna",
    artist: "HAna Tekle",
    album: "Habte semay",
    genre: "walth",
    releaseYear: new Date(),
    duration: 5.55,
    image: hana,
  },
  {
    id: 17,
    title: "Your Wings",
    artist: "Lauren Daigle",
    album: "Look Up Child",
    genre: "contemporary Christian music",
    releaseYear: new Date(),
    duration: 3.03,
    image: lauren,
  },
  {
    id: 18,
    title: "You Say",
    artist: "Lauren Daigle",
    album: "Look Up Child",
    genre: "contemporary Christian music",
    releaseYear: new Date(),
    duration: 3.03,
    image: lauren,
  },
  {
    id: 19,
    title: "Look Up Child",
    artist: "Lauren Daigle",
    album: "Look Up Child",
    genre: "contemporary Christian music",
    releaseYear: new Date(),
    duration: 3.03,
    image: lauren,
  },
  {
    id: 20,
    title: "Remember",
    artist: "Lauren Daigle",
    album: "Look Up Child",
    genre: "contemporary Christian music",
    releaseYear: new Date(),
    duration: 3.03,
    image: lauren,
  },
  {
    id: 21,
    title: "Love Like This",
    artist: "Lauren Daigle",
    album: "Look Up Child",
    genre: "contemporary Christian music",
    releaseYear: new Date(),
    duration: 3.03,
    image: lauren,
  },
  {
    id: 22,
    title: "Rescue",
    artist: "Lauren Daigle",
    album: "Look Up Child",
    genre: "contemporary Christian music",
    releaseYear: new Date(),
    duration: 3.03,
    image: lauren,
  },
];
export default allSongs;
